import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Answering Legal",
  description: "24/7 legal answering service",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Answering Legal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
      >
        {children}
      </body>
    </html>
  );
}
